{
 "title": "OSI_Dashboard",
 "time": { "from": "2022-06-11T07:54:51.000Z", "to": "2022-06-11T07:57:53.000Z" },
 "templating": {
  "list": [
   {
    "name": "buses",
    "label": "Select bus",
    "query": "SELECT column_name FROM information_schema.columns WHERE table_name='defst_combined' AND column_name NOT IN ('time_series', 't1','row_id');"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard screenshot",
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n  <a href=\"http://localhost:3000/render/d/ddyo9o5jwlj40c/osi-dashboard?orgId=1&width=1920&height=1080&kiosk=1\" target=\"_blank\" style=\"display: inline-block; padding: 10px 20px; background-color: #007bff; color: white; text-align: center; text-decoration: none; border-radius: 5px;\">\r\n    Take Screenshot\r\n  </a>\r\n</div>\r\n\r\n"
   }
  },
  {
   "title": "Email",
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n  <a href=\"http://localhost:3000/render/d/ddyo9o5jwlj40c/osi-dashboard?orgId=1&width=1920&height=1080&kiosk=1\" target=\"_blank\" style=\"display: inline-block; padding: 10px 20px; background-color: #007bff; color: white; text-align: center; text-decoration: none; border-radius: 5px;\">\r\n    Email\r\n  </a>\r\n</div>\r\n\r\n"
   }
  },
  {
   "title": "Complex Dissipating Energy Flow",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT time_series, ${buses:doublequote} FROM defst_combined LIMIT 5000"
    }
   ]
  },
  {
   "title": "Positive and Negative Slope Buses",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT positive_bus_name, negative_bus_name FROM high_der_slope LIMIT 50 "
    }
   ]
  },
  {
   "title": "Network Diagram",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 3 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "firstNotNull",
      "first",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   },
   "targets": [
    { "dataset": "Osi_Tool_DB" }
   ]
  },
  {
   "title": "Mode Metering",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT range_0_2, range_2_4, range_4_6, range_6_12 FROM mode_meter_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "Oscillation Detection time",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT detection_time FROM detection_timestamp LIMIT 50 "
    }
   ]
  },
  {
   "title": "Oscillation Source Bus",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT  positive_bus_name FROM high_der_slope LIMIT 1 "
    }
   ]
  },
  {
   "title": "Mode Plot",
   "type": "xychart",
   "gridPos": { "h": 11, "w": 8, "x": 6, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT final_matrix_real_part, final_matrix_imag_part FROM final_matrix LIMIT 50 "
    }
   ]
  },
  {
   "title": "Suspect",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT suspect FROM suspect_status LIMIT 50 "
    }
   ]
  },
  {
   "title": "Dominant Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Hz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT dom_mode FROM suspect_table ORDER BY id DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Min. damping",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT min_damp FROM suspect_table LIMIT 50 "
    }
   ]
  },
  {
   "title": "MW Oscillation at Source Bus",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT time_series, first_osci_p FROM oscillation_data LIMIT 100000000"
    }
   ]
  },
  {
   "title": "MSE Value",
   "type": "table",
   "description": "MSE Value for frequency estimation.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT source_bus, mse_value FROM mse_value LIMIT 50 "
    }
   ]
  }
 ]
}